names ={
  "村人": ["Cúnngǐn","Cunˋ ngin"],
  "杰": ["Kied","Kiedˋ"],
  "杰2": ["Kia̍t"],
  "水仔": ["Sùiè","Shuiˊ er"],
  "林老實": ["Lǐm Lòsiid","Lim Loˊ Shidˋ"],
  "阿九": ["Á-Gìu","A+ Giuˊ"],
  "林": ["Lǐm","Lim"],
  "九": ["Gìu","Giuˊ"],
  "水": ["Sùi","Shuiˊ"],
  "水2": ["Tsuí"],
  "庄人2": ["Tsng-lâng"],
  "外甥2": ["Guē-sing"],
  "甥2": ["Sing"],
  "船員": ["Sǒnǐan","Shon rhan"],
  "蝶": ["Tiab","Tiabˋ"],
  "瑪祖卡": ["Macuka","Macuka"],
  "丙": ["Bíang","Biangˋ"],
  "丙2": ["Píng"],
  "姆": ["Mé","Meˋ"],
  "Tok": ["Tok","Tok"],
  "必": ["Pickering", "Pickering"],
  "李": ["LeGendre", "LeGendre"],
  "軍官5": ["Jūnguān"],
  "劉5": ["Líu"],
  "風祭司3": ["Puljingaw"],
  "巴耶林3": ["Paljaljim"],
  "船員4": ["Crew"],
  "杭特4": ["Mr. Hunter"],
  "夫人4": ["Mrs. Hunter"]
}