names ={
  "村人": ["Cúnngǐn","Cunˋ ngin"],
  "杰": ["Kied","Kiedˋ"],
  "杰2": ["Kia̍t"],
  "水仔": ["Sùiè","Shuiˊ er"],
  "林老實": ["Lǐm Lòsiid傷長","Lim Loˊ Shidˋ"],
  "阿九": ["Á-Gìu","A+ Giuˊ"],
  "林": ["Lǐm","Lim"],
  "林2": ["Lîm"],
  "九": ["Gìu","Giuˊ"],
  "水": ["Sùi","Shuiˊ"],
  "水2": ["Tsuí"],
  "庄儂2": ["Tsng-lâng傷長"],
  "外甥2": ["Guē-sing"],
  "甥2": ["Sing"],
  "府城儂2": ["Hú-siânn lâng傷長"],
  "茶師2": ["Tê-su"],
  "趙2": ["Tiō"],
  "黃2": ["N̂g"],
  "平湖老大2": ["Pênn-ôo&nbsp;&nbsp;<br>Láu-tuā"],
  "平2": ["Pênn"],
  "平湖儂": ["Pênn-ôo-lâng傷長"],
  "船員": ["Sǒnǐan","Shon rhan"],
  "蝶": ["Tiab","Tiabˋ"],
  "蝶2": ["Tia̍p"],
  "瑪祖卡": ["Macuka","Macuka"],
  "丙": ["Bíang","Biangˋ"],
  "丙2": ["Píng"],
  "姆": ["Mé","Meˋ"],
  "Tok": ["Tok","Tok"],
  "必": ["Pickering", "Pickering"],
  "李": ["LeGendre", "LeGendre"],
  "軍官5": ["Jūnguān"],
  "劉5": ["Líu"]
}